services:
  comet:
    image: g0ldyy/comet:latest
    container_name: comet
    tty: true
    ports:
      - "8000:8000"
    environment:
      FASTAPI_HOST: 0.0.0.0
      FASTAPI_PORT: 8000
      FASTAPI_WORKERS: 1
    volumes:
      - .:/app